### ISSUE TITLE
MJS+ mod links are incorrect

### ISSUE THREAD

**Issue by kokoropaint** [sharmayu/mjg-repo#35]
I was looking to download some mods for majsoul+, but some of the links are broken.

[Page](https://repo.riichi.moe/library.html#majsoulp-mods)

I tested everything under Utilities and specifically, the **Friendly Uncle** and **Titles visible cross-server** links install the wrong mods.
(The **Anti AFK** mod also doesn't lead to a catbox link so you might want to change the download text to "github" but that's less important...)

Thanks so much for compiling these resources, I recently got into riichi mahjong (and majsoul) and they've helped a lot.

**Comment by watterle** [comment]
Done. Mods are probably not up-to-date, but at least links are correct. Shan't search through the archives to find them.
