### ISSUE TITLE
/mjg/ map

### ISSUE THREAD

**Issue by watterle** [sharmayu/mjg-repo#58]
move it to /mjg/ projects instead of newfriend pastebin after map 2.0 is posted in thread

**Comment by Furitenman** [comment]
Any news on this?

**Comment by watterle** [comment]
@shinmichaelao , any news on this?

**Comment by watterle** [comment]
everybody busy with the league start I guess

**Comment by Furitenman** [comment]
I assumed that. I will also stop a bit my contributions during the league unless something important comes up. In any case, @ me if needed.

**Comment by shinmichaelao** [comment]
new poll koko: https://forms.gle/GtoKNodZv2b45G2t5
new map koko: https://www.google.com/maps/d/u/0/edit?mid=13b8wSEmDHMLcr-bLAOwYn9uojYST3svf&usp=sharing

**Comment by watterle** [comment]
based?

**Comment by watterle** [comment]
post in thread tho
