### ISSUE TITLE
Where to play homepage

### ISSUE THREAD

**Issue by watterle** [sharmayu/mjg-repo#59]
Make it less bright than pure white

**Comment by Furitenman** [comment]
Can you be a bit more specific, please?

**Comment by watterle** [comment]
![765](https://user-images.githubusercontent.com/49875739/116046543-79368c80-a673-11eb-84c9-9bde6ad3bd02.png)
Something more similar to the grey on the left? Don't take my ramblings too seriously if they're retarded
