### ISSUE TITLE
Navigation menu dropdown on mouse hover closes dropdown inconsistently

### ISSUE THREAD

**Issue by NamaikiNaNeko** [sharmayu/mjg-repo#61]
Observed behavior: when mousing over the navigation menu bar, a dropdown menu appears. When moving down from the header to the menu items, the menu disappears if the mouse movement is not fast enough to put the cursor onto the dropdown menu items.

Clicking the header highlights the header and holds the dropdown menu open indefinitely, as expected. Issue is only in hovering the mouse over the header then moving to the dropdown list.

video:
https://files.catbox.moe/oxw7kn.webm

**Comment by Furitenman** [comment]
Hm, good catch. Gonna check the css
