### ISSUE TITLE
Issue with the "loli of the week" thing

### ISSUE THREAD

**Issue by Furitenman** [sharmayu/mjg-repo#69]
There were users complaining about the loli appearing on the main page of the repo because muh lewds and whatnot. So I thought it would be nicer if the loli would just pop-up immediately when you open the home page. It also has a 10 second timer before you can close and it refreshes every 24 hours. Opinions? Should I put a PR on it? I particularly don't care about lolis, but if it scares normies then I can go on being petty like this.
![](https://user-images.githubusercontent.com/82289213/116915152-f3ef4100-ac4b-11eb-9e0e-a5b4db575717.png)

**Comment by watterle** [comment]
How can a man be so based?

**Comment by watterle** [comment]
Still, it looks like pretty annoying so it's better to avoid it. I think the loli of the week is enough

**Comment by Furitenman** [comment]
Maybe make it just 5 seconds?

**Comment by watterle** [comment]
Nah, the very idea of a forced popup goes against the readibility of the site. Normalfags are scared enough of a still picture, so it's fine as it is

**Comment by watterle** [comment]
It'd be a great april's fool tho
