### ISSUE TITLE
Too much wasted space

### ISSUE THREAD

**Issue by kingdomfreak** [sharmayu/mjg-repo#70]
There is simply too much wasted space in the top part of the site. It can be made much more compact and better looking.
here is my recommendation:
![TrHmauCcR1vW_chrome_LcdY354th9](https://user-images.githubusercontent.com/68961104/117006097-4d0cb280-ace8-11eb-9e9d-65b4dd050dfd.png)

**Comment by sharmayu** [comment]
Don't fucking change that I use the repo on the phone

**Comment by watterle** [comment]
fuck phoneposters
